// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: walleapi/walleapi.proto

package walleapi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Entry struct {
	EntryId  int64  `protobuf:"varint,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	WriterId string `protobuf:"bytes,2,opt,name=writer_id,json=writerId,proto3" json:"writer_id,omitempty"`
	Data     []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// checksum_md5 is a rolling md5 for all `data`.
	ChecksumMd5          []byte   `protobuf:"bytes,4,opt,name=checksum_md5,json=checksumMd5,proto3" json:"checksum_md5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b522378fad0fbf4, []int{0}
}
func (m *Entry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return m.Size()
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetEntryId() int64 {
	if m != nil {
		return m.EntryId
	}
	return 0
}

func (m *Entry) GetWriterId() string {
	if m != nil {
		return m.WriterId
	}
	return ""
}

func (m *Entry) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Entry) GetChecksumMd5() []byte {
	if m != nil {
		return m.ChecksumMd5
	}
	return nil
}

type ClaimWriterRequest struct {
	StreamUri            string   `protobuf:"bytes,1,opt,name=stream_uri,json=streamUri,proto3" json:"stream_uri,omitempty"`
	LeaseMs              int64    `protobuf:"varint,2,opt,name=lease_ms,json=leaseMs,proto3" json:"lease_ms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClaimWriterRequest) Reset()         { *m = ClaimWriterRequest{} }
func (m *ClaimWriterRequest) String() string { return proto.CompactTextString(m) }
func (*ClaimWriterRequest) ProtoMessage()    {}
func (*ClaimWriterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b522378fad0fbf4, []int{1}
}
func (m *ClaimWriterRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClaimWriterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClaimWriterRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClaimWriterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClaimWriterRequest.Merge(m, src)
}
func (m *ClaimWriterRequest) XXX_Size() int {
	return m.Size()
}
func (m *ClaimWriterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClaimWriterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClaimWriterRequest proto.InternalMessageInfo

func (m *ClaimWriterRequest) GetStreamUri() string {
	if m != nil {
		return m.StreamUri
	}
	return ""
}

func (m *ClaimWriterRequest) GetLeaseMs() int64 {
	if m != nil {
		return m.LeaseMs
	}
	return 0
}

type ClaimWriterResponse struct {
	WriterId             string   `protobuf:"bytes,1,opt,name=writer_id,json=writerId,proto3" json:"writer_id,omitempty"`
	LastEntry            *Entry   `protobuf:"bytes,4,opt,name=last_entry,json=lastEntry,proto3" json:"last_entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClaimWriterResponse) Reset()         { *m = ClaimWriterResponse{} }
func (m *ClaimWriterResponse) String() string { return proto.CompactTextString(m) }
func (*ClaimWriterResponse) ProtoMessage()    {}
func (*ClaimWriterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b522378fad0fbf4, []int{2}
}
func (m *ClaimWriterResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClaimWriterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClaimWriterResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClaimWriterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClaimWriterResponse.Merge(m, src)
}
func (m *ClaimWriterResponse) XXX_Size() int {
	return m.Size()
}
func (m *ClaimWriterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClaimWriterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClaimWriterResponse proto.InternalMessageInfo

func (m *ClaimWriterResponse) GetWriterId() string {
	if m != nil {
		return m.WriterId
	}
	return ""
}

func (m *ClaimWriterResponse) GetLastEntry() *Entry {
	if m != nil {
		return m.LastEntry
	}
	return nil
}

type PutEntryRequest struct {
	StreamUri            string   `protobuf:"bytes,1,opt,name=stream_uri,json=streamUri,proto3" json:"stream_uri,omitempty"`
	Entry                *Entry   `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	CommittedEntryId     int64    `protobuf:"varint,3,opt,name=committed_entry_id,json=committedEntryId,proto3" json:"committed_entry_id,omitempty"`
	CommittedEntryMd5    []byte   `protobuf:"bytes,4,opt,name=committed_entry_md5,json=committedEntryMd5,proto3" json:"committed_entry_md5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutEntryRequest) Reset()         { *m = PutEntryRequest{} }
func (m *PutEntryRequest) String() string { return proto.CompactTextString(m) }
func (*PutEntryRequest) ProtoMessage()    {}
func (*PutEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b522378fad0fbf4, []int{3}
}
func (m *PutEntryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PutEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PutEntryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PutEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutEntryRequest.Merge(m, src)
}
func (m *PutEntryRequest) XXX_Size() int {
	return m.Size()
}
func (m *PutEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutEntryRequest proto.InternalMessageInfo

func (m *PutEntryRequest) GetStreamUri() string {
	if m != nil {
		return m.StreamUri
	}
	return ""
}

func (m *PutEntryRequest) GetEntry() *Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func (m *PutEntryRequest) GetCommittedEntryId() int64 {
	if m != nil {
		return m.CommittedEntryId
	}
	return 0
}

func (m *PutEntryRequest) GetCommittedEntryMd5() []byte {
	if m != nil {
		return m.CommittedEntryMd5
	}
	return nil
}

type PutEntryResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutEntryResponse) Reset()         { *m = PutEntryResponse{} }
func (m *PutEntryResponse) String() string { return proto.CompactTextString(m) }
func (*PutEntryResponse) ProtoMessage()    {}
func (*PutEntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b522378fad0fbf4, []int{4}
}
func (m *PutEntryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PutEntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PutEntryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PutEntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutEntryResponse.Merge(m, src)
}
func (m *PutEntryResponse) XXX_Size() int {
	return m.Size()
}
func (m *PutEntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutEntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutEntryResponse proto.InternalMessageInfo

type StreamEntriesRequest struct {
	StreamUri            string   `protobuf:"bytes,1,opt,name=stream_uri,json=streamUri,proto3" json:"stream_uri,omitempty"`
	FromEntryId          int64    `protobuf:"varint,2,opt,name=from_entry_id,json=fromEntryId,proto3" json:"from_entry_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamEntriesRequest) Reset()         { *m = StreamEntriesRequest{} }
func (m *StreamEntriesRequest) String() string { return proto.CompactTextString(m) }
func (*StreamEntriesRequest) ProtoMessage()    {}
func (*StreamEntriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b522378fad0fbf4, []int{5}
}
func (m *StreamEntriesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StreamEntriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StreamEntriesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StreamEntriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamEntriesRequest.Merge(m, src)
}
func (m *StreamEntriesRequest) XXX_Size() int {
	return m.Size()
}
func (m *StreamEntriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamEntriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamEntriesRequest proto.InternalMessageInfo

func (m *StreamEntriesRequest) GetStreamUri() string {
	if m != nil {
		return m.StreamUri
	}
	return ""
}

func (m *StreamEntriesRequest) GetFromEntryId() int64 {
	if m != nil {
		return m.FromEntryId
	}
	return 0
}

func init() {
	proto.RegisterType((*Entry)(nil), "Entry")
	proto.RegisterType((*ClaimWriterRequest)(nil), "ClaimWriterRequest")
	proto.RegisterType((*ClaimWriterResponse)(nil), "ClaimWriterResponse")
	proto.RegisterType((*PutEntryRequest)(nil), "PutEntryRequest")
	proto.RegisterType((*PutEntryResponse)(nil), "PutEntryResponse")
	proto.RegisterType((*StreamEntriesRequest)(nil), "StreamEntriesRequest")
}

func init() { proto.RegisterFile("walleapi/walleapi.proto", fileDescriptor_3b522378fad0fbf4) }

var fileDescriptor_3b522378fad0fbf4 = []byte{
	// 448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcf, 0x6e, 0x13, 0x31,
	0x10, 0xc6, 0xe3, 0xa6, 0x7f, 0xb2, 0x93, 0x56, 0xa4, 0x93, 0x22, 0x42, 0x80, 0x28, 0xac, 0x04,
	0xca, 0x01, 0x39, 0x10, 0x54, 0x09, 0x71, 0x03, 0xd4, 0x43, 0x0f, 0x45, 0x68, 0x11, 0xaa, 0xca,
	0x65, 0xe5, 0xc6, 0x86, 0x5a, 0xac, 0xbb, 0x8b, 0xed, 0x6d, 0x05, 0x4f, 0xc2, 0x43, 0xc0, 0x7b,
	0x70, 0xe4, 0x11, 0x50, 0x78, 0x11, 0x64, 0x3b, 0x7f, 0xba, 0x69, 0x0f, 0xb9, 0xcd, 0x7c, 0xb3,
	0x1a, 0xfd, 0xbe, 0xcf, 0x3b, 0x70, 0xe7, 0x92, 0x65, 0x99, 0x60, 0x85, 0x1c, 0xce, 0x0a, 0x5a,
	0xe8, 0xdc, 0xe6, 0xf1, 0x05, 0x6c, 0x1c, 0x9c, 0x5b, 0xfd, 0x0d, 0xef, 0x42, 0x43, 0xb8, 0x22,
	0x95, 0xbc, 0x43, 0xfa, 0x64, 0x50, 0x4f, 0xb6, 0x7c, 0x7f, 0xc8, 0xf1, 0x1e, 0x44, 0x97, 0x5a,
	0x5a, 0xa1, 0xdd, 0x6c, 0xad, 0x4f, 0x06, 0x51, 0xd2, 0x08, 0xc2, 0x21, 0x47, 0x84, 0x75, 0xce,
	0x2c, 0xeb, 0xd4, 0xfb, 0x64, 0xb0, 0x9d, 0xf8, 0x1a, 0x1f, 0xc2, 0xf6, 0xf8, 0x4c, 0x8c, 0xbf,
	0x98, 0x52, 0xa5, 0x8a, 0xef, 0x77, 0xd6, 0xfd, 0xac, 0x39, 0xd3, 0x8e, 0xf8, 0x7e, 0xfc, 0x16,
	0xf0, 0x4d, 0xc6, 0xa4, 0x3a, 0xf6, 0x7b, 0x12, 0xf1, 0xb5, 0x14, 0xc6, 0xe2, 0x03, 0x00, 0x63,
	0xb5, 0x60, 0x2a, 0x2d, 0xb5, 0xf4, 0x18, 0x51, 0x12, 0x05, 0xe5, 0x83, 0x96, 0x8e, 0x31, 0x13,
	0xcc, 0x88, 0x54, 0x19, 0xcf, 0x51, 0x4f, 0xb6, 0x7c, 0x7f, 0x64, 0xe2, 0x13, 0x68, 0x57, 0xf6,
	0x99, 0x22, 0x3f, 0x37, 0xa2, 0x8a, 0x4e, 0x96, 0xd0, 0x1f, 0x01, 0x64, 0xcc, 0xd8, 0xd4, 0xfb,
	0xf4, 0x90, 0xcd, 0xd1, 0x26, 0xf5, 0x71, 0x24, 0x91, 0x9b, 0xf8, 0x32, 0xfe, 0x49, 0xe0, 0xd6,
	0xbb, 0x32, 0x34, 0x2b, 0x82, 0xde, 0x87, 0x8d, 0xb0, 0x74, 0xad, 0xb2, 0x34, 0x88, 0xf8, 0x04,
	0x70, 0x9c, 0x2b, 0x25, 0xad, 0x15, 0x3c, 0x9d, 0x87, 0x5e, 0xf7, 0x86, 0x5a, 0xf3, 0xc9, 0xc1,
	0x34, 0x7d, 0x0a, 0xed, 0xe5, 0xaf, 0x17, 0x99, 0xee, 0x56, 0x3f, 0x77, 0xc9, 0x22, 0xb4, 0x16,
	0xb4, 0x21, 0x86, 0xf8, 0x04, 0xf6, 0xde, 0x7b, 0x38, 0x27, 0x4b, 0x61, 0x56, 0xb4, 0x11, 0xc3,
	0xce, 0x27, 0x9d, 0xab, 0x05, 0x63, 0x08, 0xbd, 0xe9, 0xc4, 0x29, 0xde, 0xe8, 0x17, 0x81, 0xc6,
	0xb1, 0xfb, 0xa7, 0x5e, 0x15, 0x12, 0x5f, 0x42, 0xf3, 0xca, 0x2b, 0x60, 0x9b, 0x5e, 0x7f, 0xe3,
	0xee, 0x1e, 0xbd, 0xe1, 0xa1, 0xe2, 0x1a, 0x3e, 0x83, 0xc6, 0x8c, 0x1b, 0x5b, 0x74, 0x29, 0xf0,
	0xee, 0x2e, 0xbd, 0x66, 0xaa, 0x86, 0x23, 0xd8, 0xa9, 0xd8, 0xc2, 0xdb, 0xf4, 0x26, 0x9b, 0xdd,
	0x69, 0xfe, 0x71, 0xed, 0x29, 0x79, 0xfd, 0xe2, 0xf7, 0xa4, 0x47, 0xfe, 0x4c, 0x7a, 0xe4, 0xef,
	0xa4, 0x47, 0x7e, 0xfc, 0xeb, 0xd5, 0x3e, 0x3e, 0xfe, 0x2c, 0xed, 0x59, 0x79, 0x4a, 0xc7, 0xb9,
	0x1a, 0x7e, 0xbf, 0x90, 0x8c, 0xab, 0x70, 0x24, 0x43, 0x7f, 0x21, 0xf3, 0x83, 0x39, 0xdd, 0xf4,
	0xfd, 0xf3, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3c, 0xa6, 0x48, 0x2f, 0x4c, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WalleApiClient is the client API for WalleApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalleApiClient interface {
	ClaimWriter(ctx context.Context, in *ClaimWriterRequest, opts ...grpc.CallOption) (*ClaimWriterResponse, error)
	PutEntry(ctx context.Context, in *PutEntryRequest, opts ...grpc.CallOption) (*PutEntryResponse, error)
	StreamEntries(ctx context.Context, in *StreamEntriesRequest, opts ...grpc.CallOption) (WalleApi_StreamEntriesClient, error)
}

type walleApiClient struct {
	cc *grpc.ClientConn
}

func NewWalleApiClient(cc *grpc.ClientConn) WalleApiClient {
	return &walleApiClient{cc}
}

func (c *walleApiClient) ClaimWriter(ctx context.Context, in *ClaimWriterRequest, opts ...grpc.CallOption) (*ClaimWriterResponse, error) {
	out := new(ClaimWriterResponse)
	err := c.cc.Invoke(ctx, "/WalleApi/ClaimWriter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walleApiClient) PutEntry(ctx context.Context, in *PutEntryRequest, opts ...grpc.CallOption) (*PutEntryResponse, error) {
	out := new(PutEntryResponse)
	err := c.cc.Invoke(ctx, "/WalleApi/PutEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walleApiClient) StreamEntries(ctx context.Context, in *StreamEntriesRequest, opts ...grpc.CallOption) (WalleApi_StreamEntriesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_WalleApi_serviceDesc.Streams[0], "/WalleApi/StreamEntries", opts...)
	if err != nil {
		return nil, err
	}
	x := &walleApiStreamEntriesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WalleApi_StreamEntriesClient interface {
	Recv() (*Entry, error)
	grpc.ClientStream
}

type walleApiStreamEntriesClient struct {
	grpc.ClientStream
}

func (x *walleApiStreamEntriesClient) Recv() (*Entry, error) {
	m := new(Entry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WalleApiServer is the server API for WalleApi service.
type WalleApiServer interface {
	ClaimWriter(context.Context, *ClaimWriterRequest) (*ClaimWriterResponse, error)
	PutEntry(context.Context, *PutEntryRequest) (*PutEntryResponse, error)
	StreamEntries(*StreamEntriesRequest, WalleApi_StreamEntriesServer) error
}

func RegisterWalleApiServer(s *grpc.Server, srv WalleApiServer) {
	s.RegisterService(&_WalleApi_serviceDesc, srv)
}

func _WalleApi_ClaimWriter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimWriterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalleApiServer).ClaimWriter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WalleApi/ClaimWriter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalleApiServer).ClaimWriter(ctx, req.(*ClaimWriterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalleApi_PutEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalleApiServer).PutEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WalleApi/PutEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalleApiServer).PutEntry(ctx, req.(*PutEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalleApi_StreamEntries_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEntriesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WalleApiServer).StreamEntries(m, &walleApiStreamEntriesServer{stream})
}

type WalleApi_StreamEntriesServer interface {
	Send(*Entry) error
	grpc.ServerStream
}

type walleApiStreamEntriesServer struct {
	grpc.ServerStream
}

func (x *walleApiStreamEntriesServer) Send(m *Entry) error {
	return x.ServerStream.SendMsg(m)
}

var _WalleApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "WalleApi",
	HandlerType: (*WalleApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClaimWriter",
			Handler:    _WalleApi_ClaimWriter_Handler,
		},
		{
			MethodName: "PutEntry",
			Handler:    _WalleApi_PutEntry_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEntries",
			Handler:       _WalleApi_StreamEntries_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "walleapi/walleapi.proto",
}

func (m *Entry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Entry) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.EntryId != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintWalleapi(dAtA, i, uint64(m.EntryId))
	}
	if len(m.WriterId) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintWalleapi(dAtA, i, uint64(len(m.WriterId)))
		i += copy(dAtA[i:], m.WriterId)
	}
	if len(m.Data) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintWalleapi(dAtA, i, uint64(len(m.Data)))
		i += copy(dAtA[i:], m.Data)
	}
	if len(m.ChecksumMd5) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintWalleapi(dAtA, i, uint64(len(m.ChecksumMd5)))
		i += copy(dAtA[i:], m.ChecksumMd5)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ClaimWriterRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClaimWriterRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.StreamUri) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintWalleapi(dAtA, i, uint64(len(m.StreamUri)))
		i += copy(dAtA[i:], m.StreamUri)
	}
	if m.LeaseMs != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintWalleapi(dAtA, i, uint64(m.LeaseMs))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ClaimWriterResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClaimWriterResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.WriterId) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintWalleapi(dAtA, i, uint64(len(m.WriterId)))
		i += copy(dAtA[i:], m.WriterId)
	}
	if m.LastEntry != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintWalleapi(dAtA, i, uint64(m.LastEntry.Size()))
		n1, err := m.LastEntry.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *PutEntryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PutEntryRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.StreamUri) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintWalleapi(dAtA, i, uint64(len(m.StreamUri)))
		i += copy(dAtA[i:], m.StreamUri)
	}
	if m.Entry != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintWalleapi(dAtA, i, uint64(m.Entry.Size()))
		n2, err := m.Entry.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.CommittedEntryId != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintWalleapi(dAtA, i, uint64(m.CommittedEntryId))
	}
	if len(m.CommittedEntryMd5) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintWalleapi(dAtA, i, uint64(len(m.CommittedEntryMd5)))
		i += copy(dAtA[i:], m.CommittedEntryMd5)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *PutEntryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PutEntryResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *StreamEntriesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StreamEntriesRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.StreamUri) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintWalleapi(dAtA, i, uint64(len(m.StreamUri)))
		i += copy(dAtA[i:], m.StreamUri)
	}
	if m.FromEntryId != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintWalleapi(dAtA, i, uint64(m.FromEntryId))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintWalleapi(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Entry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EntryId != 0 {
		n += 1 + sovWalleapi(uint64(m.EntryId))
	}
	l = len(m.WriterId)
	if l > 0 {
		n += 1 + l + sovWalleapi(uint64(l))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovWalleapi(uint64(l))
	}
	l = len(m.ChecksumMd5)
	if l > 0 {
		n += 1 + l + sovWalleapi(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ClaimWriterRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.StreamUri)
	if l > 0 {
		n += 1 + l + sovWalleapi(uint64(l))
	}
	if m.LeaseMs != 0 {
		n += 1 + sovWalleapi(uint64(m.LeaseMs))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ClaimWriterResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.WriterId)
	if l > 0 {
		n += 1 + l + sovWalleapi(uint64(l))
	}
	if m.LastEntry != nil {
		l = m.LastEntry.Size()
		n += 1 + l + sovWalleapi(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *PutEntryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.StreamUri)
	if l > 0 {
		n += 1 + l + sovWalleapi(uint64(l))
	}
	if m.Entry != nil {
		l = m.Entry.Size()
		n += 1 + l + sovWalleapi(uint64(l))
	}
	if m.CommittedEntryId != 0 {
		n += 1 + sovWalleapi(uint64(m.CommittedEntryId))
	}
	l = len(m.CommittedEntryMd5)
	if l > 0 {
		n += 1 + l + sovWalleapi(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *PutEntryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *StreamEntriesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.StreamUri)
	if l > 0 {
		n += 1 + l + sovWalleapi(uint64(l))
	}
	if m.FromEntryId != 0 {
		n += 1 + sovWalleapi(uint64(m.FromEntryId))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovWalleapi(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozWalleapi(x uint64) (n int) {
	return sovWalleapi(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Entry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWalleapi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Entry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Entry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EntryId", wireType)
			}
			m.EntryId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EntryId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WriterId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWalleapi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWalleapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WriterId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthWalleapi
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthWalleapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChecksumMd5", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthWalleapi
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthWalleapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChecksumMd5 = append(m.ChecksumMd5[:0], dAtA[iNdEx:postIndex]...)
			if m.ChecksumMd5 == nil {
				m.ChecksumMd5 = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWalleapi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWalleapi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWalleapi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClaimWriterRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWalleapi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClaimWriterRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClaimWriterRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWalleapi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWalleapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StreamUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeaseMs", wireType)
			}
			m.LeaseMs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LeaseMs |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipWalleapi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWalleapi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWalleapi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClaimWriterResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWalleapi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClaimWriterResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClaimWriterResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WriterId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWalleapi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWalleapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WriterId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastEntry", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWalleapi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWalleapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LastEntry == nil {
				m.LastEntry = &Entry{}
			}
			if err := m.LastEntry.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWalleapi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWalleapi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWalleapi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PutEntryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWalleapi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PutEntryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PutEntryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWalleapi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWalleapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StreamUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entry", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWalleapi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWalleapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Entry == nil {
				m.Entry = &Entry{}
			}
			if err := m.Entry.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommittedEntryId", wireType)
			}
			m.CommittedEntryId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommittedEntryId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommittedEntryMd5", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthWalleapi
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthWalleapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommittedEntryMd5 = append(m.CommittedEntryMd5[:0], dAtA[iNdEx:postIndex]...)
			if m.CommittedEntryMd5 == nil {
				m.CommittedEntryMd5 = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWalleapi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWalleapi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWalleapi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PutEntryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWalleapi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PutEntryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PutEntryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipWalleapi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWalleapi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWalleapi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StreamEntriesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWalleapi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StreamEntriesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StreamEntriesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWalleapi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWalleapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StreamUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromEntryId", wireType)
			}
			m.FromEntryId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FromEntryId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipWalleapi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWalleapi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWalleapi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipWalleapi(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowWalleapi
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWalleapi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWalleapi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthWalleapi
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthWalleapi
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowWalleapi
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipWalleapi(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthWalleapi
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthWalleapi = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowWalleapi   = fmt.Errorf("proto: integer overflow")
)
