language: go

go:
  - 1.14

services:
  - docker

install:
  - go install github.com/zviadm/tt/tt

script:
  - tt -v -short -race ./walle/...
  - tt -v -short -race ./wallelib/...
  - tt -v ./walle/itest/...
  - tt -v -bench=Bench -run=XXX ./walle/...
  - tt -v -bench=Bench -run=XXX ./wallelib/...
