language: go

go:
  - 1.14

# HAX: Fix submodule issues:
# https://stackoverflow.com/questions/15674064/how-to-fix-a-permission-denied-publickey-error-for-a-git-submodule-update-in-t
git:
  submodules: false
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

services:
  - docker

install:
  - go install github.com/zviadm/tt/tt

script:
  - tt -short -race ./walle/...
  - tt -short -race ./wallelib/...
  - tt ./walle/itest/...
  - tt -bench=Bench -run=XXX ./walle/...
  - tt -bench=Bench -run=XXX ./wallelib/...
