// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: walle/walle.proto

package walle

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	walleapi "github.com/zviadm/walle/proto/walleapi"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type NewWriterRequest struct {
	ServerId      string            `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	StreamUri     string            `protobuf:"bytes,2,opt,name=stream_uri,json=streamUri,proto3" json:"stream_uri,omitempty"`
	StreamVersion int64             `protobuf:"varint,3,opt,name=stream_version,json=streamVersion,proto3" json:"stream_version,omitempty"`
	FromServerId  string            `protobuf:"bytes,4,opt,name=from_server_id,json=fromServerId,proto3" json:"from_server_id,omitempty"`
	WriterId      walleapi.WriterId `protobuf:"bytes,5,opt,name=writer_id,json=writerId,proto3" json:"writer_id"`
	WriterAddr    string            `protobuf:"bytes,6,opt,name=writer_addr,json=writerAddr,proto3" json:"writer_addr,omitempty"`
	LeaseMs       int64             `protobuf:"varint,7,opt,name=lease_ms,json=leaseMs,proto3" json:"lease_ms,omitempty"`
}

func (m *NewWriterRequest) Reset()         { *m = NewWriterRequest{} }
func (m *NewWriterRequest) String() string { return proto.CompactTextString(m) }
func (*NewWriterRequest) ProtoMessage()    {}
func (*NewWriterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_827f2b64ddfdb030, []int{0}
}
func (m *NewWriterRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NewWriterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NewWriterRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NewWriterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewWriterRequest.Merge(m, src)
}
func (m *NewWriterRequest) XXX_Size() int {
	return m.Size()
}
func (m *NewWriterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewWriterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewWriterRequest proto.InternalMessageInfo

func (m *NewWriterRequest) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *NewWriterRequest) GetStreamUri() string {
	if m != nil {
		return m.StreamUri
	}
	return ""
}

func (m *NewWriterRequest) GetStreamVersion() int64 {
	if m != nil {
		return m.StreamVersion
	}
	return 0
}

func (m *NewWriterRequest) GetFromServerId() string {
	if m != nil {
		return m.FromServerId
	}
	return ""
}

func (m *NewWriterRequest) GetWriterId() walleapi.WriterId {
	if m != nil {
		return m.WriterId
	}
	return walleapi.WriterId{}
}

func (m *NewWriterRequest) GetWriterAddr() string {
	if m != nil {
		return m.WriterAddr
	}
	return ""
}

func (m *NewWriterRequest) GetLeaseMs() int64 {
	if m != nil {
		return m.LeaseMs
	}
	return 0
}

type NewWriterResponse struct {
}

func (m *NewWriterResponse) Reset()         { *m = NewWriterResponse{} }
func (m *NewWriterResponse) String() string { return proto.CompactTextString(m) }
func (*NewWriterResponse) ProtoMessage()    {}
func (*NewWriterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_827f2b64ddfdb030, []int{1}
}
func (m *NewWriterResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NewWriterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NewWriterResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NewWriterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewWriterResponse.Merge(m, src)
}
func (m *NewWriterResponse) XXX_Size() int {
	return m.Size()
}
func (m *NewWriterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewWriterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewWriterResponse proto.InternalMessageInfo

type WriterInfoRequest struct {
	ServerId      string `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	StreamUri     string `protobuf:"bytes,2,opt,name=stream_uri,json=streamUri,proto3" json:"stream_uri,omitempty"`
	StreamVersion int64  `protobuf:"varint,3,opt,name=stream_version,json=streamVersion,proto3" json:"stream_version,omitempty"`
	FromServerId  string `protobuf:"bytes,4,opt,name=from_server_id,json=fromServerId,proto3" json:"from_server_id,omitempty"`
}

func (m *WriterInfoRequest) Reset()         { *m = WriterInfoRequest{} }
func (m *WriterInfoRequest) String() string { return proto.CompactTextString(m) }
func (*WriterInfoRequest) ProtoMessage()    {}
func (*WriterInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_827f2b64ddfdb030, []int{2}
}
func (m *WriterInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WriterInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WriterInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WriterInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriterInfoRequest.Merge(m, src)
}
func (m *WriterInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *WriterInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriterInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriterInfoRequest proto.InternalMessageInfo

func (m *WriterInfoRequest) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *WriterInfoRequest) GetStreamUri() string {
	if m != nil {
		return m.StreamUri
	}
	return ""
}

func (m *WriterInfoRequest) GetStreamVersion() int64 {
	if m != nil {
		return m.StreamVersion
	}
	return 0
}

func (m *WriterInfoRequest) GetFromServerId() string {
	if m != nil {
		return m.FromServerId
	}
	return ""
}

type WriterInfoResponse struct {
	WriterId         walleapi.WriterId `protobuf:"bytes,1,opt,name=writer_id,json=writerId,proto3" json:"writer_id"`
	WriterAddr       string            `protobuf:"bytes,2,opt,name=writer_addr,json=writerAddr,proto3" json:"writer_addr,omitempty"`
	LeaseMs          int64             `protobuf:"varint,3,opt,name=lease_ms,json=leaseMs,proto3" json:"lease_ms,omitempty"`
	RemainingLeaseMs int64             `protobuf:"varint,4,opt,name=remaining_lease_ms,json=remainingLeaseMs,proto3" json:"remaining_lease_ms,omitempty"`
	StreamVersion    int64             `protobuf:"varint,5,opt,name=stream_version,json=streamVersion,proto3" json:"stream_version,omitempty"`
}

func (m *WriterInfoResponse) Reset()         { *m = WriterInfoResponse{} }
func (m *WriterInfoResponse) String() string { return proto.CompactTextString(m) }
func (*WriterInfoResponse) ProtoMessage()    {}
func (*WriterInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_827f2b64ddfdb030, []int{3}
}
func (m *WriterInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WriterInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WriterInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WriterInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriterInfoResponse.Merge(m, src)
}
func (m *WriterInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *WriterInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WriterInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WriterInfoResponse proto.InternalMessageInfo

func (m *WriterInfoResponse) GetWriterId() walleapi.WriterId {
	if m != nil {
		return m.WriterId
	}
	return walleapi.WriterId{}
}

func (m *WriterInfoResponse) GetWriterAddr() string {
	if m != nil {
		return m.WriterAddr
	}
	return ""
}

func (m *WriterInfoResponse) GetLeaseMs() int64 {
	if m != nil {
		return m.LeaseMs
	}
	return 0
}

func (m *WriterInfoResponse) GetRemainingLeaseMs() int64 {
	if m != nil {
		return m.RemainingLeaseMs
	}
	return 0
}

func (m *WriterInfoResponse) GetStreamVersion() int64 {
	if m != nil {
		return m.StreamVersion
	}
	return 0
}

type PutEntryInternalRequest struct {
	ServerId         string          `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	StreamUri        string          `protobuf:"bytes,2,opt,name=stream_uri,json=streamUri,proto3" json:"stream_uri,omitempty"`
	StreamVersion    int64           `protobuf:"varint,3,opt,name=stream_version,json=streamVersion,proto3" json:"stream_version,omitempty"`
	FromServerId     string          `protobuf:"bytes,4,opt,name=from_server_id,json=fromServerId,proto3" json:"from_server_id,omitempty"`
	IgnoreLeaseRenew bool            `protobuf:"varint,5,opt,name=ignore_lease_renew,json=ignoreLeaseRenew,proto3" json:"ignore_lease_renew,omitempty"`
	CommittedEntryId int64           `protobuf:"varint,6,opt,name=committed_entry_id,json=committedEntryId,proto3" json:"committed_entry_id,omitempty"`
	CommittedEntryXX uint64          `protobuf:"varint,7,opt,name=committed_entry_x_x,json=committedEntryXX,proto3" json:"committed_entry_x_x,omitempty"`
	Entry            *walleapi.Entry `protobuf:"bytes,8,opt,name=entry,proto3" json:"entry,omitempty"`
}

func (m *PutEntryInternalRequest) Reset()         { *m = PutEntryInternalRequest{} }
func (m *PutEntryInternalRequest) String() string { return proto.CompactTextString(m) }
func (*PutEntryInternalRequest) ProtoMessage()    {}
func (*PutEntryInternalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_827f2b64ddfdb030, []int{4}
}
func (m *PutEntryInternalRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PutEntryInternalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PutEntryInternalRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PutEntryInternalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutEntryInternalRequest.Merge(m, src)
}
func (m *PutEntryInternalRequest) XXX_Size() int {
	return m.Size()
}
func (m *PutEntryInternalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutEntryInternalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutEntryInternalRequest proto.InternalMessageInfo

func (m *PutEntryInternalRequest) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *PutEntryInternalRequest) GetStreamUri() string {
	if m != nil {
		return m.StreamUri
	}
	return ""
}

func (m *PutEntryInternalRequest) GetStreamVersion() int64 {
	if m != nil {
		return m.StreamVersion
	}
	return 0
}

func (m *PutEntryInternalRequest) GetFromServerId() string {
	if m != nil {
		return m.FromServerId
	}
	return ""
}

func (m *PutEntryInternalRequest) GetIgnoreLeaseRenew() bool {
	if m != nil {
		return m.IgnoreLeaseRenew
	}
	return false
}

func (m *PutEntryInternalRequest) GetCommittedEntryId() int64 {
	if m != nil {
		return m.CommittedEntryId
	}
	return 0
}

func (m *PutEntryInternalRequest) GetCommittedEntryXX() uint64 {
	if m != nil {
		return m.CommittedEntryXX
	}
	return 0
}

func (m *PutEntryInternalRequest) GetEntry() *walleapi.Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type PutEntryInternalResponse struct {
}

func (m *PutEntryInternalResponse) Reset()         { *m = PutEntryInternalResponse{} }
func (m *PutEntryInternalResponse) String() string { return proto.CompactTextString(m) }
func (*PutEntryInternalResponse) ProtoMessage()    {}
func (*PutEntryInternalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_827f2b64ddfdb030, []int{5}
}
func (m *PutEntryInternalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PutEntryInternalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PutEntryInternalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PutEntryInternalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutEntryInternalResponse.Merge(m, src)
}
func (m *PutEntryInternalResponse) XXX_Size() int {
	return m.Size()
}
func (m *PutEntryInternalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutEntryInternalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutEntryInternalResponse proto.InternalMessageInfo

type TailEntriesRequest struct {
	ServerId      string `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	StreamUri     string `protobuf:"bytes,2,opt,name=stream_uri,json=streamUri,proto3" json:"stream_uri,omitempty"`
	StreamVersion int64  `protobuf:"varint,3,opt,name=stream_version,json=streamVersion,proto3" json:"stream_version,omitempty"`
	FromServerId  string `protobuf:"bytes,4,opt,name=from_server_id,json=fromServerId,proto3" json:"from_server_id,omitempty"`
}

func (m *TailEntriesRequest) Reset()         { *m = TailEntriesRequest{} }
func (m *TailEntriesRequest) String() string { return proto.CompactTextString(m) }
func (*TailEntriesRequest) ProtoMessage()    {}
func (*TailEntriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_827f2b64ddfdb030, []int{6}
}
func (m *TailEntriesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TailEntriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TailEntriesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TailEntriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TailEntriesRequest.Merge(m, src)
}
func (m *TailEntriesRequest) XXX_Size() int {
	return m.Size()
}
func (m *TailEntriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TailEntriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TailEntriesRequest proto.InternalMessageInfo

func (m *TailEntriesRequest) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *TailEntriesRequest) GetStreamUri() string {
	if m != nil {
		return m.StreamUri
	}
	return ""
}

func (m *TailEntriesRequest) GetStreamVersion() int64 {
	if m != nil {
		return m.StreamVersion
	}
	return 0
}

func (m *TailEntriesRequest) GetFromServerId() string {
	if m != nil {
		return m.FromServerId
	}
	return ""
}

type ReadEntriesRequest struct {
	ServerId      string `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	StreamUri     string `protobuf:"bytes,2,opt,name=stream_uri,json=streamUri,proto3" json:"stream_uri,omitempty"`
	StreamVersion int64  `protobuf:"varint,3,opt,name=stream_version,json=streamVersion,proto3" json:"stream_version,omitempty"`
	FromServerId  string `protobuf:"bytes,4,opt,name=from_server_id,json=fromServerId,proto3" json:"from_server_id,omitempty"`
	StartEntryId  int64  `protobuf:"varint,5,opt,name=start_entry_id,json=startEntryId,proto3" json:"start_entry_id,omitempty"`
	EndEntryId    int64  `protobuf:"varint,6,opt,name=end_entry_id,json=endEntryId,proto3" json:"end_entry_id,omitempty"`
}

func (m *ReadEntriesRequest) Reset()         { *m = ReadEntriesRequest{} }
func (m *ReadEntriesRequest) String() string { return proto.CompactTextString(m) }
func (*ReadEntriesRequest) ProtoMessage()    {}
func (*ReadEntriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_827f2b64ddfdb030, []int{7}
}
func (m *ReadEntriesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReadEntriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReadEntriesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReadEntriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadEntriesRequest.Merge(m, src)
}
func (m *ReadEntriesRequest) XXX_Size() int {
	return m.Size()
}
func (m *ReadEntriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadEntriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadEntriesRequest proto.InternalMessageInfo

func (m *ReadEntriesRequest) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *ReadEntriesRequest) GetStreamUri() string {
	if m != nil {
		return m.StreamUri
	}
	return ""
}

func (m *ReadEntriesRequest) GetStreamVersion() int64 {
	if m != nil {
		return m.StreamVersion
	}
	return 0
}

func (m *ReadEntriesRequest) GetFromServerId() string {
	if m != nil {
		return m.FromServerId
	}
	return ""
}

func (m *ReadEntriesRequest) GetStartEntryId() int64 {
	if m != nil {
		return m.StartEntryId
	}
	return 0
}

func (m *ReadEntriesRequest) GetEndEntryId() int64 {
	if m != nil {
		return m.EndEntryId
	}
	return 0
}

func init() {
	proto.RegisterType((*NewWriterRequest)(nil), "NewWriterRequest")
	proto.RegisterType((*NewWriterResponse)(nil), "NewWriterResponse")
	proto.RegisterType((*WriterInfoRequest)(nil), "WriterInfoRequest")
	proto.RegisterType((*WriterInfoResponse)(nil), "WriterInfoResponse")
	proto.RegisterType((*PutEntryInternalRequest)(nil), "PutEntryInternalRequest")
	proto.RegisterType((*PutEntryInternalResponse)(nil), "PutEntryInternalResponse")
	proto.RegisterType((*TailEntriesRequest)(nil), "TailEntriesRequest")
	proto.RegisterType((*ReadEntriesRequest)(nil), "ReadEntriesRequest")
}

func init() { proto.RegisterFile("walle/walle.proto", fileDescriptor_827f2b64ddfdb030) }

var fileDescriptor_827f2b64ddfdb030 = []byte{
	// 622 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xf5, 0xa4, 0x49, 0x1a, 0xdf, 0xf6, 0xab, 0x92, 0x9b, 0x45, 0x5d, 0x7f, 0xe0, 0x46, 0x06,
	0xa4, 0x2e, 0xca, 0x04, 0x15, 0x24, 0x56, 0x2c, 0xa8, 0xc4, 0x22, 0x12, 0x20, 0x64, 0x7e, 0x5a,
	0xb1, 0xb1, 0xdc, 0x7a, 0x1a, 0x46, 0x8a, 0xc7, 0x65, 0x3c, 0x69, 0x0a, 0x7b, 0xf6, 0x3c, 0x00,
	0x2c, 0x78, 0x9b, 0x4a, 0x6c, 0x2a, 0xb1, 0x61, 0x85, 0x50, 0x2b, 0xde, 0x03, 0x79, 0xc6, 0x49,
	0xd3, 0x98, 0x22, 0xb1, 0xcb, 0xc6, 0x9a, 0x39, 0xe7, 0x68, 0xe6, 0xfe, 0x1c, 0xdf, 0x81, 0xd6,
	0x28, 0x1a, 0x0c, 0x58, 0x57, 0x7f, 0xe9, 0xa1, 0x4c, 0x55, 0xea, 0x42, 0x3f, 0xed, 0xa7, 0xc5,
	0x7a, 0x55, 0x13, 0xd1, 0x21, 0xef, 0x8e, 0x17, 0x86, 0xf0, 0x3f, 0x54, 0xa0, 0xf9, 0x94, 0x8d,
	0x76, 0x24, 0x57, 0x4c, 0x06, 0xec, 0xed, 0x90, 0x65, 0x0a, 0xff, 0x07, 0x3b, 0x63, 0xf2, 0x88,
	0xc9, 0x90, 0xc7, 0x0e, 0xe9, 0x90, 0x0d, 0x3b, 0x68, 0x18, 0xa0, 0x17, 0xe3, 0x75, 0x80, 0x4c,
	0x49, 0x16, 0x25, 0xe1, 0x50, 0x72, 0xa7, 0xa2, 0x59, 0xdb, 0x20, 0x2f, 0x25, 0xc7, 0x5b, 0xb0,
	0x52, 0xd0, 0x47, 0x4c, 0x66, 0x3c, 0x15, 0xce, 0x42, 0x87, 0x6c, 0x2c, 0x04, 0xff, 0x19, 0xf4,
	0x95, 0x01, 0xf1, 0x26, 0xac, 0x1c, 0xc8, 0x34, 0x09, 0x2f, 0xee, 0xa9, 0xea, 0x93, 0x96, 0x73,
	0xf4, 0xf9, 0xf8, 0xae, 0x4d, 0xb0, 0x47, 0x3a, 0xb2, 0x5c, 0x50, 0xeb, 0x90, 0x8d, 0xa5, 0x2d,
	0x9b, 0x9a, 0x58, 0x7b, 0xf1, 0x76, 0xf5, 0xe4, 0xc7, 0xba, 0x15, 0x34, 0x46, 0xc5, 0x1e, 0xd7,
	0x61, 0xa9, 0x50, 0x47, 0x71, 0x2c, 0x9d, 0xba, 0x3e, 0x10, 0x0c, 0xf4, 0x30, 0x8e, 0x25, 0xae,
	0x41, 0x63, 0xc0, 0xa2, 0x8c, 0x85, 0x49, 0xe6, 0x2c, 0xea, 0xa8, 0x16, 0xf5, 0xfe, 0x49, 0xe6,
	0xb7, 0xa1, 0x35, 0x55, 0x86, 0xec, 0x30, 0x15, 0x19, 0xf3, 0x3f, 0x11, 0x68, 0x15, 0xb7, 0x89,
	0x83, 0x74, 0xde, 0xaa, 0xe3, 0x7f, 0x23, 0x80, 0xd3, 0xe1, 0x99, 0xa8, 0x2f, 0x17, 0x8d, 0xfc,
	0x63, 0xd1, 0x2a, 0x7f, 0x2d, 0xda, 0xc2, 0xa5, 0xa2, 0xe1, 0x26, 0xa0, 0x64, 0x49, 0xc4, 0x05,
	0x17, 0xfd, 0x70, 0x22, 0xaa, 0x6a, 0x51, 0x73, 0xc2, 0x3c, 0x2e, 0xd4, 0xe5, 0xdc, 0x6b, 0x7f,
	0xc8, 0xdd, 0xff, 0x5a, 0x81, 0xd5, 0x67, 0x43, 0xf5, 0x48, 0x28, 0xf9, 0xae, 0x27, 0x14, 0x93,
	0x22, 0x1a, 0xcc, 0xa1, 0x31, 0x91, 0xf7, 0x45, 0x2a, 0x59, 0x91, 0xb6, 0x64, 0x82, 0x8d, 0x74,
	0x3e, 0x8d, 0xa0, 0x69, 0x18, 0x9d, 0x76, 0x90, 0xe3, 0xb9, 0x7a, 0x3f, 0x4d, 0x12, 0xae, 0x14,
	0x8b, 0x43, 0x96, 0x27, 0x96, 0x9f, 0x5b, 0x37, 0x75, 0x9a, 0x30, 0x26, 0xe3, 0x18, 0x6f, 0x43,
	0x7b, 0x56, 0x7d, 0x1c, 0x1e, 0x6b, 0xc3, 0x56, 0x67, 0xe5, 0xbb, 0xbb, 0x78, 0x0d, 0x6a, 0x5a,
	0xe4, 0x34, 0x74, 0xab, 0xeb, 0x54, 0x13, 0x81, 0x01, 0x7d, 0x17, 0x9c, 0x72, 0x31, 0x0b, 0x7b,
	0x7f, 0x26, 0x80, 0x2f, 0x22, 0x3e, 0xc8, 0x59, 0xce, 0xb2, 0xb9, 0xf3, 0xf7, 0x2f, 0x02, 0x18,
	0xb0, 0x28, 0x9e, 0xd3, 0xf8, 0x72, 0x55, 0xa6, 0x22, 0xa9, 0x2e, 0x5a, 0x6a, 0x0c, 0xbd, 0xac,
	0xd1, 0x71, 0x3b, 0x3b, 0xb0, 0xcc, 0x44, 0xa9, 0xed, 0xc0, 0xc4, 0xb8, 0xe1, 0x5b, 0x5f, 0x2a,
	0x50, 0xdb, 0xc9, 0xc7, 0x32, 0xde, 0x03, 0x7b, 0x32, 0x85, 0xb0, 0x45, 0x67, 0x07, 0xb3, 0x8b,
	0xb4, 0x3c, 0xa4, 0x2c, 0xbc, 0x0f, 0x70, 0x31, 0x06, 0x10, 0x69, 0x69, 0x64, 0xb9, 0x6d, 0x5a,
	0x9e, 0x13, 0xbe, 0x85, 0x3d, 0x68, 0xce, 0x9a, 0x03, 0x1d, 0x7a, 0xc5, 0xcf, 0xe7, 0xae, 0xd1,
	0x2b, 0x9d, 0x64, 0x21, 0x85, 0xa5, 0x29, 0x2b, 0x61, 0x9b, 0x96, 0x8d, 0xe5, 0x16, 0xd6, 0xf4,
	0xad, 0x3b, 0x24, 0xd7, 0x4f, 0xb5, 0x16, 0xdb, 0xb4, 0xdc, 0xe8, 0x69, 0xfd, 0xf6, 0x83, 0x93,
	0x33, 0x8f, 0x9c, 0x9e, 0x79, 0xe4, 0xe7, 0x99, 0x47, 0x3e, 0x9e, 0x7b, 0xd6, 0xe9, 0xb9, 0x67,
	0x7d, 0x3f, 0xf7, 0xac, 0xd7, 0x37, 0xfa, 0x5c, 0xbd, 0x19, 0xee, 0xd1, 0xfd, 0x34, 0xe9, 0xbe,
	0x3f, 0xe2, 0x51, 0x9c, 0x98, 0x37, 0xae, 0xab, 0x1f, 0x38, 0xb3, 0xde, 0xab, 0xeb, 0xcd, 0xdd,
	0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x91, 0x2b, 0xaf, 0x27, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WalleClient is the client API for Walle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalleClient interface {
	NewWriter(ctx context.Context, in *NewWriterRequest, opts ...grpc.CallOption) (*NewWriterResponse, error)
	WriterInfo(ctx context.Context, in *WriterInfoRequest, opts ...grpc.CallOption) (*WriterInfoResponse, error)
	PutEntryInternal(ctx context.Context, in *PutEntryInternalRequest, opts ...grpc.CallOption) (*PutEntryInternalResponse, error)
	// Returns last committed entry and all following uncommitted entries from the server.
	// There are never any gaps in uncommitted entries.
	TailEntries(ctx context.Context, in *TailEntriesRequest, opts ...grpc.CallOption) (Walle_TailEntriesClient, error)
	// NOTE: ReadEntries only returns committed entries. If it hits a GAP or end of the stream,
	// it will return NOT_FOUND error. Returns entries in range: [start_id...end_id). Can also
	// return early if streamed data is too large. Caller can make another call to fetch
	// rest of the entries.
	ReadEntries(ctx context.Context, in *ReadEntriesRequest, opts ...grpc.CallOption) (Walle_ReadEntriesClient, error)
}

type walleClient struct {
	cc *grpc.ClientConn
}

func NewWalleClient(cc *grpc.ClientConn) WalleClient {
	return &walleClient{cc}
}

func (c *walleClient) NewWriter(ctx context.Context, in *NewWriterRequest, opts ...grpc.CallOption) (*NewWriterResponse, error) {
	out := new(NewWriterResponse)
	err := c.cc.Invoke(ctx, "/Walle/NewWriter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walleClient) WriterInfo(ctx context.Context, in *WriterInfoRequest, opts ...grpc.CallOption) (*WriterInfoResponse, error) {
	out := new(WriterInfoResponse)
	err := c.cc.Invoke(ctx, "/Walle/WriterInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walleClient) PutEntryInternal(ctx context.Context, in *PutEntryInternalRequest, opts ...grpc.CallOption) (*PutEntryInternalResponse, error) {
	out := new(PutEntryInternalResponse)
	err := c.cc.Invoke(ctx, "/Walle/PutEntryInternal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walleClient) TailEntries(ctx context.Context, in *TailEntriesRequest, opts ...grpc.CallOption) (Walle_TailEntriesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Walle_serviceDesc.Streams[0], "/Walle/TailEntries", opts...)
	if err != nil {
		return nil, err
	}
	x := &walleTailEntriesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Walle_TailEntriesClient interface {
	Recv() (*walleapi.Entry, error)
	grpc.ClientStream
}

type walleTailEntriesClient struct {
	grpc.ClientStream
}

func (x *walleTailEntriesClient) Recv() (*walleapi.Entry, error) {
	m := new(walleapi.Entry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *walleClient) ReadEntries(ctx context.Context, in *ReadEntriesRequest, opts ...grpc.CallOption) (Walle_ReadEntriesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Walle_serviceDesc.Streams[1], "/Walle/ReadEntries", opts...)
	if err != nil {
		return nil, err
	}
	x := &walleReadEntriesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Walle_ReadEntriesClient interface {
	Recv() (*walleapi.Entry, error)
	grpc.ClientStream
}

type walleReadEntriesClient struct {
	grpc.ClientStream
}

func (x *walleReadEntriesClient) Recv() (*walleapi.Entry, error) {
	m := new(walleapi.Entry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WalleServer is the server API for Walle service.
type WalleServer interface {
	NewWriter(context.Context, *NewWriterRequest) (*NewWriterResponse, error)
	WriterInfo(context.Context, *WriterInfoRequest) (*WriterInfoResponse, error)
	PutEntryInternal(context.Context, *PutEntryInternalRequest) (*PutEntryInternalResponse, error)
	// Returns last committed entry and all following uncommitted entries from the server.
	// There are never any gaps in uncommitted entries.
	TailEntries(*TailEntriesRequest, Walle_TailEntriesServer) error
	// NOTE: ReadEntries only returns committed entries. If it hits a GAP or end of the stream,
	// it will return NOT_FOUND error. Returns entries in range: [start_id...end_id). Can also
	// return early if streamed data is too large. Caller can make another call to fetch
	// rest of the entries.
	ReadEntries(*ReadEntriesRequest, Walle_ReadEntriesServer) error
}

// UnimplementedWalleServer can be embedded to have forward compatible implementations.
type UnimplementedWalleServer struct {
}

func (*UnimplementedWalleServer) NewWriter(ctx context.Context, req *NewWriterRequest) (*NewWriterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewWriter not implemented")
}
func (*UnimplementedWalleServer) WriterInfo(ctx context.Context, req *WriterInfoRequest) (*WriterInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriterInfo not implemented")
}
func (*UnimplementedWalleServer) PutEntryInternal(ctx context.Context, req *PutEntryInternalRequest) (*PutEntryInternalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutEntryInternal not implemented")
}
func (*UnimplementedWalleServer) TailEntries(req *TailEntriesRequest, srv Walle_TailEntriesServer) error {
	return status.Errorf(codes.Unimplemented, "method TailEntries not implemented")
}
func (*UnimplementedWalleServer) ReadEntries(req *ReadEntriesRequest, srv Walle_ReadEntriesServer) error {
	return status.Errorf(codes.Unimplemented, "method ReadEntries not implemented")
}

func RegisterWalleServer(s *grpc.Server, srv WalleServer) {
	s.RegisterService(&_Walle_serviceDesc, srv)
}

func _Walle_NewWriter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewWriterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalleServer).NewWriter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Walle/NewWriter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalleServer).NewWriter(ctx, req.(*NewWriterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Walle_WriterInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriterInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalleServer).WriterInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Walle/WriterInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalleServer).WriterInfo(ctx, req.(*WriterInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Walle_PutEntryInternal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutEntryInternalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalleServer).PutEntryInternal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Walle/PutEntryInternal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalleServer).PutEntryInternal(ctx, req.(*PutEntryInternalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Walle_TailEntries_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TailEntriesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WalleServer).TailEntries(m, &walleTailEntriesServer{stream})
}

type Walle_TailEntriesServer interface {
	Send(*walleapi.Entry) error
	grpc.ServerStream
}

type walleTailEntriesServer struct {
	grpc.ServerStream
}

func (x *walleTailEntriesServer) Send(m *walleapi.Entry) error {
	return x.ServerStream.SendMsg(m)
}

func _Walle_ReadEntries_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadEntriesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WalleServer).ReadEntries(m, &walleReadEntriesServer{stream})
}

type Walle_ReadEntriesServer interface {
	Send(*walleapi.Entry) error
	grpc.ServerStream
}

type walleReadEntriesServer struct {
	grpc.ServerStream
}

func (x *walleReadEntriesServer) Send(m *walleapi.Entry) error {
	return x.ServerStream.SendMsg(m)
}

var _Walle_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Walle",
	HandlerType: (*WalleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewWriter",
			Handler:    _Walle_NewWriter_Handler,
		},
		{
			MethodName: "WriterInfo",
			Handler:    _Walle_WriterInfo_Handler,
		},
		{
			MethodName: "PutEntryInternal",
			Handler:    _Walle_PutEntryInternal_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TailEntries",
			Handler:       _Walle_TailEntries_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReadEntries",
			Handler:       _Walle_ReadEntries_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "walle/walle.proto",
}

func (m *NewWriterRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NewWriterRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NewWriterRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LeaseMs != 0 {
		i = encodeVarintWalle(dAtA, i, uint64(m.LeaseMs))
		i--
		dAtA[i] = 0x38
	}
	if len(m.WriterAddr) > 0 {
		i -= len(m.WriterAddr)
		copy(dAtA[i:], m.WriterAddr)
		i = encodeVarintWalle(dAtA, i, uint64(len(m.WriterAddr)))
		i--
		dAtA[i] = 0x32
	}
	{
		size, err := m.WriterId.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintWalle(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.FromServerId) > 0 {
		i -= len(m.FromServerId)
		copy(dAtA[i:], m.FromServerId)
		i = encodeVarintWalle(dAtA, i, uint64(len(m.FromServerId)))
		i--
		dAtA[i] = 0x22
	}
	if m.StreamVersion != 0 {
		i = encodeVarintWalle(dAtA, i, uint64(m.StreamVersion))
		i--
		dAtA[i] = 0x18
	}
	if len(m.StreamUri) > 0 {
		i -= len(m.StreamUri)
		copy(dAtA[i:], m.StreamUri)
		i = encodeVarintWalle(dAtA, i, uint64(len(m.StreamUri)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ServerId) > 0 {
		i -= len(m.ServerId)
		copy(dAtA[i:], m.ServerId)
		i = encodeVarintWalle(dAtA, i, uint64(len(m.ServerId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *NewWriterResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NewWriterResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NewWriterResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *WriterInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WriterInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WriterInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FromServerId) > 0 {
		i -= len(m.FromServerId)
		copy(dAtA[i:], m.FromServerId)
		i = encodeVarintWalle(dAtA, i, uint64(len(m.FromServerId)))
		i--
		dAtA[i] = 0x22
	}
	if m.StreamVersion != 0 {
		i = encodeVarintWalle(dAtA, i, uint64(m.StreamVersion))
		i--
		dAtA[i] = 0x18
	}
	if len(m.StreamUri) > 0 {
		i -= len(m.StreamUri)
		copy(dAtA[i:], m.StreamUri)
		i = encodeVarintWalle(dAtA, i, uint64(len(m.StreamUri)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ServerId) > 0 {
		i -= len(m.ServerId)
		copy(dAtA[i:], m.ServerId)
		i = encodeVarintWalle(dAtA, i, uint64(len(m.ServerId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *WriterInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WriterInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WriterInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.StreamVersion != 0 {
		i = encodeVarintWalle(dAtA, i, uint64(m.StreamVersion))
		i--
		dAtA[i] = 0x28
	}
	if m.RemainingLeaseMs != 0 {
		i = encodeVarintWalle(dAtA, i, uint64(m.RemainingLeaseMs))
		i--
		dAtA[i] = 0x20
	}
	if m.LeaseMs != 0 {
		i = encodeVarintWalle(dAtA, i, uint64(m.LeaseMs))
		i--
		dAtA[i] = 0x18
	}
	if len(m.WriterAddr) > 0 {
		i -= len(m.WriterAddr)
		copy(dAtA[i:], m.WriterAddr)
		i = encodeVarintWalle(dAtA, i, uint64(len(m.WriterAddr)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.WriterId.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintWalle(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PutEntryInternalRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PutEntryInternalRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PutEntryInternalRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Entry != nil {
		{
			size, err := m.Entry.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintWalle(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	if m.CommittedEntryXX != 0 {
		i = encodeVarintWalle(dAtA, i, uint64(m.CommittedEntryXX))
		i--
		dAtA[i] = 0x38
	}
	if m.CommittedEntryId != 0 {
		i = encodeVarintWalle(dAtA, i, uint64(m.CommittedEntryId))
		i--
		dAtA[i] = 0x30
	}
	if m.IgnoreLeaseRenew {
		i--
		if m.IgnoreLeaseRenew {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if len(m.FromServerId) > 0 {
		i -= len(m.FromServerId)
		copy(dAtA[i:], m.FromServerId)
		i = encodeVarintWalle(dAtA, i, uint64(len(m.FromServerId)))
		i--
		dAtA[i] = 0x22
	}
	if m.StreamVersion != 0 {
		i = encodeVarintWalle(dAtA, i, uint64(m.StreamVersion))
		i--
		dAtA[i] = 0x18
	}
	if len(m.StreamUri) > 0 {
		i -= len(m.StreamUri)
		copy(dAtA[i:], m.StreamUri)
		i = encodeVarintWalle(dAtA, i, uint64(len(m.StreamUri)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ServerId) > 0 {
		i -= len(m.ServerId)
		copy(dAtA[i:], m.ServerId)
		i = encodeVarintWalle(dAtA, i, uint64(len(m.ServerId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PutEntryInternalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PutEntryInternalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PutEntryInternalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *TailEntriesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TailEntriesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TailEntriesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FromServerId) > 0 {
		i -= len(m.FromServerId)
		copy(dAtA[i:], m.FromServerId)
		i = encodeVarintWalle(dAtA, i, uint64(len(m.FromServerId)))
		i--
		dAtA[i] = 0x22
	}
	if m.StreamVersion != 0 {
		i = encodeVarintWalle(dAtA, i, uint64(m.StreamVersion))
		i--
		dAtA[i] = 0x18
	}
	if len(m.StreamUri) > 0 {
		i -= len(m.StreamUri)
		copy(dAtA[i:], m.StreamUri)
		i = encodeVarintWalle(dAtA, i, uint64(len(m.StreamUri)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ServerId) > 0 {
		i -= len(m.ServerId)
		copy(dAtA[i:], m.ServerId)
		i = encodeVarintWalle(dAtA, i, uint64(len(m.ServerId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ReadEntriesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReadEntriesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReadEntriesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EndEntryId != 0 {
		i = encodeVarintWalle(dAtA, i, uint64(m.EndEntryId))
		i--
		dAtA[i] = 0x30
	}
	if m.StartEntryId != 0 {
		i = encodeVarintWalle(dAtA, i, uint64(m.StartEntryId))
		i--
		dAtA[i] = 0x28
	}
	if len(m.FromServerId) > 0 {
		i -= len(m.FromServerId)
		copy(dAtA[i:], m.FromServerId)
		i = encodeVarintWalle(dAtA, i, uint64(len(m.FromServerId)))
		i--
		dAtA[i] = 0x22
	}
	if m.StreamVersion != 0 {
		i = encodeVarintWalle(dAtA, i, uint64(m.StreamVersion))
		i--
		dAtA[i] = 0x18
	}
	if len(m.StreamUri) > 0 {
		i -= len(m.StreamUri)
		copy(dAtA[i:], m.StreamUri)
		i = encodeVarintWalle(dAtA, i, uint64(len(m.StreamUri)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ServerId) > 0 {
		i -= len(m.ServerId)
		copy(dAtA[i:], m.ServerId)
		i = encodeVarintWalle(dAtA, i, uint64(len(m.ServerId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintWalle(dAtA []byte, offset int, v uint64) int {
	offset -= sovWalle(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *NewWriterRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ServerId)
	if l > 0 {
		n += 1 + l + sovWalle(uint64(l))
	}
	l = len(m.StreamUri)
	if l > 0 {
		n += 1 + l + sovWalle(uint64(l))
	}
	if m.StreamVersion != 0 {
		n += 1 + sovWalle(uint64(m.StreamVersion))
	}
	l = len(m.FromServerId)
	if l > 0 {
		n += 1 + l + sovWalle(uint64(l))
	}
	l = m.WriterId.Size()
	n += 1 + l + sovWalle(uint64(l))
	l = len(m.WriterAddr)
	if l > 0 {
		n += 1 + l + sovWalle(uint64(l))
	}
	if m.LeaseMs != 0 {
		n += 1 + sovWalle(uint64(m.LeaseMs))
	}
	return n
}

func (m *NewWriterResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *WriterInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ServerId)
	if l > 0 {
		n += 1 + l + sovWalle(uint64(l))
	}
	l = len(m.StreamUri)
	if l > 0 {
		n += 1 + l + sovWalle(uint64(l))
	}
	if m.StreamVersion != 0 {
		n += 1 + sovWalle(uint64(m.StreamVersion))
	}
	l = len(m.FromServerId)
	if l > 0 {
		n += 1 + l + sovWalle(uint64(l))
	}
	return n
}

func (m *WriterInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.WriterId.Size()
	n += 1 + l + sovWalle(uint64(l))
	l = len(m.WriterAddr)
	if l > 0 {
		n += 1 + l + sovWalle(uint64(l))
	}
	if m.LeaseMs != 0 {
		n += 1 + sovWalle(uint64(m.LeaseMs))
	}
	if m.RemainingLeaseMs != 0 {
		n += 1 + sovWalle(uint64(m.RemainingLeaseMs))
	}
	if m.StreamVersion != 0 {
		n += 1 + sovWalle(uint64(m.StreamVersion))
	}
	return n
}

func (m *PutEntryInternalRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ServerId)
	if l > 0 {
		n += 1 + l + sovWalle(uint64(l))
	}
	l = len(m.StreamUri)
	if l > 0 {
		n += 1 + l + sovWalle(uint64(l))
	}
	if m.StreamVersion != 0 {
		n += 1 + sovWalle(uint64(m.StreamVersion))
	}
	l = len(m.FromServerId)
	if l > 0 {
		n += 1 + l + sovWalle(uint64(l))
	}
	if m.IgnoreLeaseRenew {
		n += 2
	}
	if m.CommittedEntryId != 0 {
		n += 1 + sovWalle(uint64(m.CommittedEntryId))
	}
	if m.CommittedEntryXX != 0 {
		n += 1 + sovWalle(uint64(m.CommittedEntryXX))
	}
	if m.Entry != nil {
		l = m.Entry.Size()
		n += 1 + l + sovWalle(uint64(l))
	}
	return n
}

func (m *PutEntryInternalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *TailEntriesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ServerId)
	if l > 0 {
		n += 1 + l + sovWalle(uint64(l))
	}
	l = len(m.StreamUri)
	if l > 0 {
		n += 1 + l + sovWalle(uint64(l))
	}
	if m.StreamVersion != 0 {
		n += 1 + sovWalle(uint64(m.StreamVersion))
	}
	l = len(m.FromServerId)
	if l > 0 {
		n += 1 + l + sovWalle(uint64(l))
	}
	return n
}

func (m *ReadEntriesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ServerId)
	if l > 0 {
		n += 1 + l + sovWalle(uint64(l))
	}
	l = len(m.StreamUri)
	if l > 0 {
		n += 1 + l + sovWalle(uint64(l))
	}
	if m.StreamVersion != 0 {
		n += 1 + sovWalle(uint64(m.StreamVersion))
	}
	l = len(m.FromServerId)
	if l > 0 {
		n += 1 + l + sovWalle(uint64(l))
	}
	if m.StartEntryId != 0 {
		n += 1 + sovWalle(uint64(m.StartEntryId))
	}
	if m.EndEntryId != 0 {
		n += 1 + sovWalle(uint64(m.EndEntryId))
	}
	return n
}

func sovWalle(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozWalle(x uint64) (n int) {
	return sovWalle(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *NewWriterRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWalle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NewWriterRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NewWriterRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWalle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWalle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWalle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWalle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StreamUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamVersion", wireType)
			}
			m.StreamVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StreamVersion |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromServerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWalle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWalle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromServerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WriterId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWalle
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWalle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.WriterId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WriterAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWalle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWalle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WriterAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeaseMs", wireType)
			}
			m.LeaseMs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LeaseMs |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipWalle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWalle
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWalle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NewWriterResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWalle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NewWriterResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NewWriterResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipWalle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWalle
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWalle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WriterInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWalle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WriterInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WriterInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWalle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWalle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWalle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWalle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StreamUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamVersion", wireType)
			}
			m.StreamVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StreamVersion |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromServerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWalle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWalle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromServerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWalle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWalle
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWalle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WriterInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWalle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WriterInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WriterInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WriterId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWalle
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWalle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.WriterId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WriterAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWalle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWalle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WriterAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeaseMs", wireType)
			}
			m.LeaseMs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LeaseMs |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainingLeaseMs", wireType)
			}
			m.RemainingLeaseMs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RemainingLeaseMs |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamVersion", wireType)
			}
			m.StreamVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StreamVersion |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipWalle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWalle
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWalle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PutEntryInternalRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWalle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PutEntryInternalRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PutEntryInternalRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWalle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWalle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWalle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWalle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StreamUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamVersion", wireType)
			}
			m.StreamVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StreamVersion |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromServerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWalle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWalle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromServerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IgnoreLeaseRenew", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IgnoreLeaseRenew = bool(v != 0)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommittedEntryId", wireType)
			}
			m.CommittedEntryId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommittedEntryId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommittedEntryXX", wireType)
			}
			m.CommittedEntryXX = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommittedEntryXX |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entry", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWalle
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWalle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Entry == nil {
				m.Entry = &walleapi.Entry{}
			}
			if err := m.Entry.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWalle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWalle
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWalle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PutEntryInternalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWalle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PutEntryInternalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PutEntryInternalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipWalle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWalle
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWalle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TailEntriesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWalle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TailEntriesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TailEntriesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWalle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWalle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWalle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWalle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StreamUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamVersion", wireType)
			}
			m.StreamVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StreamVersion |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromServerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWalle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWalle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromServerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWalle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWalle
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWalle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReadEntriesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWalle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReadEntriesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReadEntriesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWalle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWalle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWalle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWalle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StreamUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamVersion", wireType)
			}
			m.StreamVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StreamVersion |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromServerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWalle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWalle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromServerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartEntryId", wireType)
			}
			m.StartEntryId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartEntryId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndEntryId", wireType)
			}
			m.EndEntryId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndEntryId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipWalle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWalle
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWalle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipWalle(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowWalle
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWalle
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthWalle
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupWalle
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthWalle
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthWalle        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowWalle          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupWalle = fmt.Errorf("proto: unexpected end of group")
)
