// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: topomgr/topomgr.proto

package topomgr

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	walleapi "github.com/zviadm/walle/proto/walleapi"
	grpc "google.golang.org/grpc"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FetchTopologyRequest struct {
	ClusterUri           string   `protobuf:"bytes,1,opt,name=cluster_uri,json=clusterUri,proto3" json:"cluster_uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchTopologyRequest) Reset()         { *m = FetchTopologyRequest{} }
func (m *FetchTopologyRequest) String() string { return proto.CompactTextString(m) }
func (*FetchTopologyRequest) ProtoMessage()    {}
func (*FetchTopologyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b9802c6f2bebbad, []int{0}
}
func (m *FetchTopologyRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FetchTopologyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FetchTopologyRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FetchTopologyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchTopologyRequest.Merge(m, src)
}
func (m *FetchTopologyRequest) XXX_Size() int {
	return m.Size()
}
func (m *FetchTopologyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchTopologyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchTopologyRequest proto.InternalMessageInfo

func (m *FetchTopologyRequest) GetClusterUri() string {
	if m != nil {
		return m.ClusterUri
	}
	return ""
}

type UpdateServerInfoRequest struct {
	ClusterUri           string               `protobuf:"bytes,1,opt,name=cluster_uri,json=clusterUri,proto3" json:"cluster_uri,omitempty"`
	ServerId             string               `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServerInfo           *walleapi.ServerInfo `protobuf:"bytes,3,opt,name=server_info,json=serverInfo,proto3" json:"server_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateServerInfoRequest) Reset()         { *m = UpdateServerInfoRequest{} }
func (m *UpdateServerInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateServerInfoRequest) ProtoMessage()    {}
func (*UpdateServerInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b9802c6f2bebbad, []int{1}
}
func (m *UpdateServerInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UpdateServerInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UpdateServerInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UpdateServerInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateServerInfoRequest.Merge(m, src)
}
func (m *UpdateServerInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *UpdateServerInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateServerInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateServerInfoRequest proto.InternalMessageInfo

func (m *UpdateServerInfoRequest) GetClusterUri() string {
	if m != nil {
		return m.ClusterUri
	}
	return ""
}

func (m *UpdateServerInfoRequest) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *UpdateServerInfoRequest) GetServerInfo() *walleapi.ServerInfo {
	if m != nil {
		return m.ServerInfo
	}
	return nil
}

type UpdateServerIdsRequest struct {
	ClusterUri           string   `protobuf:"bytes,1,opt,name=cluster_uri,json=clusterUri,proto3" json:"cluster_uri,omitempty"`
	StreamUri            string   `protobuf:"bytes,2,opt,name=stream_uri,json=streamUri,proto3" json:"stream_uri,omitempty"`
	ServerIds            []string `protobuf:"bytes,3,rep,name=server_ids,json=serverIds,proto3" json:"server_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateServerIdsRequest) Reset()         { *m = UpdateServerIdsRequest{} }
func (m *UpdateServerIdsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateServerIdsRequest) ProtoMessage()    {}
func (*UpdateServerIdsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b9802c6f2bebbad, []int{2}
}
func (m *UpdateServerIdsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UpdateServerIdsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UpdateServerIdsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UpdateServerIdsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateServerIdsRequest.Merge(m, src)
}
func (m *UpdateServerIdsRequest) XXX_Size() int {
	return m.Size()
}
func (m *UpdateServerIdsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateServerIdsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateServerIdsRequest proto.InternalMessageInfo

func (m *UpdateServerIdsRequest) GetClusterUri() string {
	if m != nil {
		return m.ClusterUri
	}
	return ""
}

func (m *UpdateServerIdsRequest) GetStreamUri() string {
	if m != nil {
		return m.StreamUri
	}
	return ""
}

func (m *UpdateServerIdsRequest) GetServerIds() []string {
	if m != nil {
		return m.ServerIds
	}
	return nil
}

type UpdateServerIdsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateServerIdsResponse) Reset()         { *m = UpdateServerIdsResponse{} }
func (m *UpdateServerIdsResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateServerIdsResponse) ProtoMessage()    {}
func (*UpdateServerIdsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b9802c6f2bebbad, []int{3}
}
func (m *UpdateServerIdsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UpdateServerIdsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UpdateServerIdsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UpdateServerIdsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateServerIdsResponse.Merge(m, src)
}
func (m *UpdateServerIdsResponse) XXX_Size() int {
	return m.Size()
}
func (m *UpdateServerIdsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateServerIdsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateServerIdsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*FetchTopologyRequest)(nil), "FetchTopologyRequest")
	proto.RegisterType((*UpdateServerInfoRequest)(nil), "UpdateServerInfoRequest")
	proto.RegisterType((*UpdateServerIdsRequest)(nil), "UpdateServerIdsRequest")
	proto.RegisterType((*UpdateServerIdsResponse)(nil), "UpdateServerIdsResponse")
}

func init() { proto.RegisterFile("topomgr/topomgr.proto", fileDescriptor_4b9802c6f2bebbad) }

var fileDescriptor_4b9802c6f2bebbad = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x6a, 0xc2, 0x40,
	0x10, 0x75, 0x2b, 0x94, 0x66, 0x42, 0x69, 0x59, 0xaa, 0xa6, 0x91, 0xa6, 0x12, 0x28, 0x78, 0x28,
	0x1b, 0xd0, 0x83, 0xf7, 0x42, 0x05, 0x0f, 0xbd, 0xd8, 0x7a, 0xe9, 0x45, 0xa2, 0x59, 0x63, 0x20,
	0xc9, 0xa6, 0xbb, 0x1b, 0xc5, 0xde, 0xfb, 0x0f, 0xfd, 0xa4, 0x1e, 0x4b, 0xbf, 0xa0, 0xd8, 0x1f,
	0x29, 0x66, 0xdd, 0x52, 0x45, 0xc1, 0xd3, 0xce, 0xbc, 0xc7, 0xec, 0xbc, 0x79, 0x33, 0x50, 0x91,
	0x2c, 0x63, 0x49, 0xc8, 0xbd, 0xf5, 0x4b, 0x32, 0xce, 0x24, 0xb3, 0xeb, 0x21, 0x63, 0x61, 0x4c,
	0xbd, 0x22, 0x1b, 0xe5, 0x13, 0x8f, 0x26, 0x99, 0x5c, 0xac, 0xc9, 0xda, 0xdc, 0x8f, 0x63, 0xea,
	0x67, 0x91, 0xa7, 0x03, 0x45, 0xb8, 0x1d, 0xb8, 0xe8, 0x52, 0x39, 0x9e, 0x3e, 0xb1, 0x8c, 0xc5,
	0x2c, 0x5c, 0xf4, 0xe9, 0x4b, 0x4e, 0x85, 0xc4, 0xd7, 0x60, 0x8e, 0xe3, 0x5c, 0x48, 0xca, 0x87,
	0x39, 0x8f, 0x2c, 0xd4, 0x40, 0x4d, 0xa3, 0x0f, 0x6b, 0x68, 0xc0, 0x23, 0xf7, 0x0d, 0x41, 0x6d,
	0x90, 0x05, 0xbe, 0xa4, 0x8f, 0x94, 0xcf, 0x28, 0xef, 0xa5, 0x13, 0x76, 0x68, 0x31, 0xae, 0x83,
	0x21, 0x8a, 0xaa, 0x61, 0x14, 0x58, 0x47, 0x05, 0x7d, 0xa2, 0x80, 0x5e, 0x80, 0x6f, 0xc1, 0xd4,
	0x64, 0x3a, 0x61, 0x56, 0xb9, 0x81, 0x9a, 0x66, 0xcb, 0x24, 0xff, 0xda, 0x80, 0xf8, 0x8b, 0xdd,
	0x39, 0x54, 0x37, 0x64, 0x04, 0xe2, 0x60, 0x15, 0x57, 0x00, 0x42, 0x72, 0xea, 0x27, 0x05, 0xaf,
	0x64, 0x18, 0x0a, 0xd1, 0xb4, 0x16, 0x29, 0xac, 0x72, 0xa3, 0x5c, 0xd0, 0xba, 0x8b, 0x7b, 0xb9,
	0x35, 0xff, 0xaa, 0xb1, 0xc8, 0x58, 0x2a, 0x68, 0xeb, 0x0b, 0x81, 0xb9, 0x32, 0xf4, 0xc1, 0x4f,
	0xfd, 0x90, 0x72, 0xdc, 0x86, 0xd3, 0x0d, 0x93, 0x71, 0x85, 0xec, 0x32, 0xdd, 0x36, 0x88, 0x46,
	0xdc, 0x12, 0xee, 0xc2, 0xf9, 0xb6, 0xbf, 0xd8, 0x22, 0x7b, 0x2c, 0xb7, 0xab, 0x44, 0xad, 0x9f,
	0xe8, 0xf5, 0x93, 0xfb, 0xd5, 0xfa, 0x8b, 0x7f, 0xce, 0xb6, 0x74, 0xe2, 0x1a, 0xd9, 0x6d, 0x99,
	0x6d, 0x91, 0x3d, 0x23, 0xb9, 0xa5, 0xbb, 0xce, 0xc7, 0xd2, 0x41, 0x9f, 0x4b, 0x07, 0x7d, 0x2f,
	0x1d, 0xf4, 0xfe, 0xe3, 0x94, 0x9e, 0x6f, 0xc2, 0x48, 0x4e, 0xf3, 0x11, 0x19, 0xb3, 0xc4, 0x7b,
	0x9d, 0x45, 0x7e, 0x90, 0xa8, 0xeb, 0x52, 0x27, 0xa8, 0xcf, 0x73, 0x74, 0x5c, 0xa4, 0xed, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x20, 0x75, 0x9f, 0x32, 0xb8, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TopoManagerClient is the client API for TopoManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TopoManagerClient interface {
	FetchTopology(ctx context.Context, in *FetchTopologyRequest, opts ...grpc.CallOption) (*walleapi.Topology, error)
	// TODO(zviad): These APIs are experimental. Most likely they will need to be
	// tweaked or renamed.
	UpdateServerInfo(ctx context.Context, in *UpdateServerInfoRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	UpdateServerIds(ctx context.Context, in *UpdateServerIdsRequest, opts ...grpc.CallOption) (*UpdateServerIdsResponse, error)
}

type topoManagerClient struct {
	cc *grpc.ClientConn
}

func NewTopoManagerClient(cc *grpc.ClientConn) TopoManagerClient {
	return &topoManagerClient{cc}
}

func (c *topoManagerClient) FetchTopology(ctx context.Context, in *FetchTopologyRequest, opts ...grpc.CallOption) (*walleapi.Topology, error) {
	out := new(walleapi.Topology)
	err := c.cc.Invoke(ctx, "/TopoManager/FetchTopology", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topoManagerClient) UpdateServerInfo(ctx context.Context, in *UpdateServerInfoRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/TopoManager/UpdateServerInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topoManagerClient) UpdateServerIds(ctx context.Context, in *UpdateServerIdsRequest, opts ...grpc.CallOption) (*UpdateServerIdsResponse, error) {
	out := new(UpdateServerIdsResponse)
	err := c.cc.Invoke(ctx, "/TopoManager/UpdateServerIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TopoManagerServer is the server API for TopoManager service.
type TopoManagerServer interface {
	FetchTopology(context.Context, *FetchTopologyRequest) (*walleapi.Topology, error)
	// TODO(zviad): These APIs are experimental. Most likely they will need to be
	// tweaked or renamed.
	UpdateServerInfo(context.Context, *UpdateServerInfoRequest) (*empty.Empty, error)
	UpdateServerIds(context.Context, *UpdateServerIdsRequest) (*UpdateServerIdsResponse, error)
}

func RegisterTopoManagerServer(s *grpc.Server, srv TopoManagerServer) {
	s.RegisterService(&_TopoManager_serviceDesc, srv)
}

func _TopoManager_FetchTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchTopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopoManagerServer).FetchTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TopoManager/FetchTopology",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopoManagerServer).FetchTopology(ctx, req.(*FetchTopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopoManager_UpdateServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopoManagerServer).UpdateServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TopoManager/UpdateServerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopoManagerServer).UpdateServerInfo(ctx, req.(*UpdateServerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopoManager_UpdateServerIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServerIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopoManagerServer).UpdateServerIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TopoManager/UpdateServerIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopoManagerServer).UpdateServerIds(ctx, req.(*UpdateServerIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TopoManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TopoManager",
	HandlerType: (*TopoManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchTopology",
			Handler:    _TopoManager_FetchTopology_Handler,
		},
		{
			MethodName: "UpdateServerInfo",
			Handler:    _TopoManager_UpdateServerInfo_Handler,
		},
		{
			MethodName: "UpdateServerIds",
			Handler:    _TopoManager_UpdateServerIds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "topomgr/topomgr.proto",
}

func (m *FetchTopologyRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FetchTopologyRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ClusterUri) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTopomgr(dAtA, i, uint64(len(m.ClusterUri)))
		i += copy(dAtA[i:], m.ClusterUri)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *UpdateServerInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateServerInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ClusterUri) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTopomgr(dAtA, i, uint64(len(m.ClusterUri)))
		i += copy(dAtA[i:], m.ClusterUri)
	}
	if len(m.ServerId) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTopomgr(dAtA, i, uint64(len(m.ServerId)))
		i += copy(dAtA[i:], m.ServerId)
	}
	if m.ServerInfo != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintTopomgr(dAtA, i, uint64(m.ServerInfo.Size()))
		n1, err := m.ServerInfo.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *UpdateServerIdsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateServerIdsRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ClusterUri) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTopomgr(dAtA, i, uint64(len(m.ClusterUri)))
		i += copy(dAtA[i:], m.ClusterUri)
	}
	if len(m.StreamUri) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTopomgr(dAtA, i, uint64(len(m.StreamUri)))
		i += copy(dAtA[i:], m.StreamUri)
	}
	if len(m.ServerIds) > 0 {
		for _, s := range m.ServerIds {
			dAtA[i] = 0x1a
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *UpdateServerIdsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateServerIdsResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintTopomgr(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *FetchTopologyRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ClusterUri)
	if l > 0 {
		n += 1 + l + sovTopomgr(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *UpdateServerInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ClusterUri)
	if l > 0 {
		n += 1 + l + sovTopomgr(uint64(l))
	}
	l = len(m.ServerId)
	if l > 0 {
		n += 1 + l + sovTopomgr(uint64(l))
	}
	if m.ServerInfo != nil {
		l = m.ServerInfo.Size()
		n += 1 + l + sovTopomgr(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *UpdateServerIdsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ClusterUri)
	if l > 0 {
		n += 1 + l + sovTopomgr(uint64(l))
	}
	l = len(m.StreamUri)
	if l > 0 {
		n += 1 + l + sovTopomgr(uint64(l))
	}
	if len(m.ServerIds) > 0 {
		for _, s := range m.ServerIds {
			l = len(s)
			n += 1 + l + sovTopomgr(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *UpdateServerIdsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovTopomgr(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozTopomgr(x uint64) (n int) {
	return sovTopomgr(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FetchTopologyRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTopomgr
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FetchTopologyRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FetchTopologyRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopomgr
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTopomgr
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTopomgr
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClusterUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTopomgr(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTopomgr
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTopomgr
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UpdateServerInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTopomgr
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdateServerInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdateServerInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopomgr
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTopomgr
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTopomgr
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClusterUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopomgr
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTopomgr
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTopomgr
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServerInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopomgr
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTopomgr
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTopomgr
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ServerInfo == nil {
				m.ServerInfo = &walleapi.ServerInfo{}
			}
			if err := m.ServerInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTopomgr(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTopomgr
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTopomgr
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UpdateServerIdsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTopomgr
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdateServerIdsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdateServerIdsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopomgr
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTopomgr
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTopomgr
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClusterUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopomgr
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTopomgr
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTopomgr
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StreamUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServerIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopomgr
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTopomgr
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTopomgr
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServerIds = append(m.ServerIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTopomgr(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTopomgr
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTopomgr
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UpdateServerIdsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTopomgr
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdateServerIdsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdateServerIdsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTopomgr(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTopomgr
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTopomgr
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTopomgr(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTopomgr
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTopomgr
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTopomgr
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTopomgr
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthTopomgr
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowTopomgr
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipTopomgr(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthTopomgr
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthTopomgr = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTopomgr   = fmt.Errorf("proto: integer overflow")
)
